version: '3.5'
services:
  elasticsearch:
    container_name: elasticsearch_dev
    image: elasticsearch:7.6.1
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    networks:
      - elk
  logstash:
    container_name: logstash
    image: logstash:7.6.1
    ports:
      - 5044:5044
    volumes:
      - ./logstash.conf:/conf-dir/logstash.conf
    command: logstash -f /conf-dir/logstash.conf
    depends_on:
      - elasticsearch
    networks:
      - elk
  kibana:
    container_name: kibana
    image: kibana:7.6.1
    ports:
      - 5601:5601
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  elasticsearch:
    name: elaticsearch
    driver: local

networks:
  elk:
    name: elk
    driver: bridge