apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    run: jaeger-node
spec:
  selector:
    run: jaeger-node
  ports:
  - port: 16686
    protocol: TCP
    name: jaeger-ui
  type: LoadBalancer