version: '3.5'
services:
  nats_server:
    image: nats:latest
    container_name: nats_server_dev
    ports:
      - 4222:4222
      - 8222:8222
    networks:
      - MSAnet1

networks:
  MSAnet1:
    name: MSAnet1
    driver: bridge