version: '3.5'
services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.8.0
    volumes:
      - /Users/parkjinhong/log/gateway/:/usr/share/filebeat/log/gateway/
      - ./filebeat.yml:/usr/share/filebeat/filebeat.yml
    networks:
      - elk

networks:
  elk:
    name: elk
    driver: bridge