version: '3.5'
services:
  rabbitmq_server:
    image: rabbitmq:3-management
    container_name: rabbitmq_server_dev
    ports:
      - 15672:15672
      - 5672:5672
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}