version: '3.5'
services:
  auth_microservice:
    container_name: auth_microservice_dev
    image: auth_microservice_image:latest
    volumes:
      - db:/var/lib/mysql
    environment:
      - NATS=nats_server_dev:4222
      - GO111MODULE=on
      - DB_PASSWORD=auth_microservice_db_password
    networks:
      - MSAnet1

networks:
  MSAnet1:
    name: MSAnet1
    driver: bridge

volumes:
  db:
    driver: local
